version: '3'

services:
  # User Interface
  # mocknet-dashboard:
  #   image: mocknet/mocknet-dashboard
  #   container_name: dashboard
  #   build:
  #     context: ./mocknet-dashboard
  #   ports:
  #     - 8080:8080

  # Monitoring Tool
  # monitor:
  #   image: mocknet/monitor
  #   container_name: monitor
  #   build:
  #     context: ./monitor
  #   ports:
  #     - 1111:1111

  # Microservices
  users:
    image: mocknet/users
    container_name: users
    depends_on:
      - mongo
    build:
      context: ./microservices/users
    environment:
      REQUEST_MODE: ${REQUEST_MODE}
      ENV: ${ENV}
      PORT: ${MS_PORT_USERS}
    ports:
      - ${MS_PORT_USERS}:${MS_PORT_USERS}

  orders:
    image: mocknet/orders
    container_name: orders
    depends_on:
      - mongo
    build:
      context: ./microservices/orders
    environment:
      REQUEST_MODE: ${REQUEST_MODE}
      ENV: ${ENV}
      PORT: ${MS_PORT_ORDERS}
    ports:
      - ${MS_PORT_ORDERS}:${MS_PORT_ORDERS}

  items:
    image: mocknet/items
    container_name: items
    depends_on:
      - mongo
    build:
      context: ./microservices/items
    environment:
      REQUEST_MODE: ${REQUEST_MODE}
      ENV: ${ENV}
      PORT: ${MS_PORT_ITEMS}
    ports:
      - ${MS_PORT_ITEMS}:${MS_PORT_ITEMS}

  inventory:
    image: mocknet/inventory
    container_name: inventory
    depends_on:
      - mongo
    build:
      context: ./microservices/inventory
    environment:
      REQUEST_MODE: ${REQUEST_MODE}
      ENV: ${ENV}
      PORT: ${MS_PORT_INVENTORY}
    ports:
      - ${MS_PORT_INVENTORY}:${MS_PORT_INVENTORY}

  email:
    image: mocknet/email
    container_name: email
    depends_on:
      - mongo
    build:
      context: ./microservices/email
    environment:
      REQUEST_MODE: ${REQUEST_MODE}
      ENV: ${ENV}
      PORT: ${MS_PORT_EMAIL}
    ports:
      - ${MS_PORT_EMAIL}:${MS_PORT_EMAIL}

  payment:
    image: mocknet/payment
    container_name: payment
    depends_on:
      - mongo
    build:
      context: ./microservices/payment
    environment:
      REQUEST_MODE: ${REQUEST_MODE}
      ENV: ${ENV}
      PORT: ${MS_PORT_PAYMENT}
    ports:
      - ${MS_PORT_PAYMENT}:${MS_PORT_PAYMENT}

  # Database
  mongo:
    container_name: mongo
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - '27017:27017'

  # mongo-express:
  #   image: mongo-express
  #   container_name: mexpress
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  #     - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
  #     - ME_CONFIG_BASICAUTH_USERNAME=mexpress
  #     - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
  #   links:
  #     - mongo
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"

volumes:
  mongodb:
  mongodb_config:
