version: '3'

services:
# User Interface
  mocknet-dashboard:
    container_name: mocknet-dashboard
    build:
      context: ./mocknet-dashboard
    environment:
      NODE_ENV: production
    ports:
      - 3000:80

# Monitoring Tool
  monitor:
    container_name: monitor
    build:
      context: ./monitor
    environment:
      NODE_ENV: production
    ports:
      - 1111:1111

# Microservices
  users:
    container_name: users
    build:
      context: ./users
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080

  orders:
    container_name: orders
    build:
      context: ./orders
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081

# Database
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
