version: '3'

services:
  # User Interface
  mocknet-dashboard:
    image: mocknet/mocknet-dashboard
    container_name: dashboard
    build:
      context: ./mocknet-dashboard
    ports:
      - 8080:8080

  # Monitoring Tool
  monitor:
    image: mocknet/monitor
    container_name: monitor
    build:
      context: ./monitor
    ports:
      - 1111:1111

  # Microservices
  users:
    image: mocknet/users
    container_name: users
    build:
      context: ./microservices/users
    ports:
      - 5000:5000

  orders:
    image: mocknet/orders
    container_name: orders
    build:
      context: ./microservices/orders
    ports:
      - 5001:5001

  items:
    image: mocknet/items
    container_name: items
    build:
      context: ./microservices/items
    ports:
      - 5002:5002

  payment:
    image: mocknet/payment
    container_name: payment
    build:
      context: ./microservices/payment
    ports:
      - 5003:5003

  inventory:
    image: mocknet/inventory
    container_name: inventory
    build:
      context: ./microservices/inventory
    ports:
      - 5004:5004

  email:
    image: mocknet/email
    container_name: email
    build:
      context: ./microservices/email
    ports:
      - 5005:5005

  # Database
  mongo:
    container_name: mongo
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"

volumes:
  mongodb:
  mongodb_config:
